MacTrack/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('members.urls')),
    path('taskTimer/', include('timesheets.urls')),
    path('reports/', include('reports.urls')),
    path('projects/', include('projects.urls')),
    path('fitting_floor/', include('fitting_floor.urls')),
]

fitting_floor/urls.py
from django.urls import path

from fitting_floor import views
from .views import DeleteFittingTask, UpdateFittingTask

app_name = 'ff'

urlpatterns = [
    path("", views.fitting_floor_home, name="Fitting_Floor"),
    path("add_fitting_task", views.addFittingTask, name="Create_Floor_Task"),
    path("edit_task/<int:taskId>", views.testingFF, name="Edit_Floor_Task"),
    path("delete_task/<int:pk>/", DeleteFittingTask.as_view(), name="Delete_Floor_Task"),
]

main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.landingPage, name="Home"),
    path("login/", views.login_page, name="Log"),
]

fitting_floor/models.py
from django.db import models
from projects.models import Project
from datetime import timedelta
from timesheets.models import AncillaryJobCode
from django.contrib.auth.models import User

# Create your models here.

class FittingTask(models.Model):

    job_code = models.ForeignKey(
        Project, 
        null=False, 
        blank=False,
        on_delete=models.PROTECT,
        limit_choices_to={"is_active": True}
    )
    ancillary_code = models.ForeignKey(
        AncillaryJobCode,  
        null=True, 
        blank=True, 
        on_delete=models.SET_NULL
    )

    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,
        related_name="fitting_task")
    notes = models.TextField(max_length=240, blank=True, null=True)
    elapsed_time = models.DurationField(blank=True, null=True)
    time_started = models.TimeField(blank=True, null=True)
    time_stopped = models.TimeField(blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_edited = models.DateTimeField(auto_now=True)
    is_running = models.BooleanField(default=False)
    is_ongoing = models.BooleanField(default=True)

    class Meta:
        ordering = ['date_created', 'user']

    def __str__(self) -> str:
        return str(self.user) + ": " + str(self.job_code) + " - " + str(self.elapsed_time)

    def get_elapsed_time(self):
        """Get elapsed time of task"""
        started = self.time_started
        stopped = self.time_stopped

        if started and stopped:
            # Format the elapsed_time as (hrs, min, seconds)
            recent_elapsed_time = self.time_stopped - self.time_started

            if self.elapsed_time:
                total_elapsed_time = self.elapsed_time + recent_elapsed_time
            else:
                total_elapsed_time = recent_elapsed_time

            # Convert the total_elapsed_time (which is a timedelta object) to minutes and hours
            minutes, seconds = divmod(total_elapsed_time.seconds, 60)
            hours, minutes = divmod(minutes, 60)

            # convert the timedelta to time format and save to the object
            total_elapsed_time = timedelta(hours=hours, minutes=minutes, seconds=seconds)

            self.elapsed_time = total_elapsed_time
            self.save()  # Don't forget to save the changes

            # return the time difference in formatted
            return total_elapsed_time

        return self.elapsed_time

fitting_floor/forms.py
from django import forms
from .models import FittingTask
from django.utils import timezone

# Crispy Forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field

# Models 
from django.contrib.auth.models import User
from members.models import User_Profile


class Fitting_Task_Form(forms.ModelForm):
    class Meta:
        model = FittingTask
        # fields = ("user", "job_code", "ancillary_code", "time_started")
        fields = ("user", "job_code", "ancillary_code", "time_started", "time_stopped")

        widgets = {
            "user": forms.Select(
                attrs={
                    "class": "form-select",
                    "placeholder": "Fitter",
                }
            ),
            "job_code": forms.Select(
                attrs={
                    "class": "form-select",
                    "placeholder": "Job Code",
                }
            ),
            "description": forms.Select(attrs={"class": "form-select"}),
            "ancillary_code": forms.Select(
                attrs={
                    "class": "form-select",
                    "placeholder": "Ancillary Code",
                }
            ),
            "time_started": forms.TimeInput(
                attrs={
                    'type': 'time',
                    "class": "form-control",
                }
            ),
            "time_stopped": forms.TimeInput(
                attrs={
                    'type': 'time',
                    "class": "form-control",
                }
            ),
        }

    def __init__(self,*args, **kwargs):
        super(Fitting_Task_Form, self).__init__(*args, **kwargs)
        
        # Crispy
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_class = 'form-horizontal'

        self.helper.add_input(Submit('submit', 'Submit'))
        
        # Get the User IDs for user profiles where role is 'Fit'
        fitter_user_ids = User_Profile.objects.filter(role="Fit").values_list('user', flat=True)
        
        # Now filter the User queryset to those User IDs
        self.fields['user'].queryset = User.objects.filter(id__in=fitter_user_ids)



class Fitting_Task_Edit_Form(forms.ModelForm):
    class Meta:
        model = FittingTask
        # fields = ("user", "job_code", "ancillary_code", "time_started")
        fields = ("user", "job_code", "ancillary_code", "time_started", "time_stopped", "notes")

        widgets = {
            "user": forms.Select(
                attrs={
                    "class": "form-select",
                    "placeholder": "Fitter",
                }
            ),
            "job_code": forms.Select(
                attrs={
                    "class": "form-select",
                    "placeholder": "Job Code",
                }
            ),
            "description": forms.Select(
                attrs={
                    "class": "form-select",
                    "placeholder": "Desription",
                }
            ),
            "ancillary_code": forms.Select(
                attrs={
                    "class": "form-select",
                    "placeholder": "Ancillary Code",
                }
            ),
            "time_started": forms.TimeInput(
                attrs={
                    'type': 'time',
                    "class": "form-control",
                }
            ),
            "time_stopped": forms.TimeInput(
                attrs={
                    'type': 'time',
                    "class": "form-control",
                }
            ),
            "notes": forms.TextInput(
                attrs={
                    'type': 'text-area',
                    "class": "form-control",
                }
            ),
            
        }

    def __init__(self,*args, **kwargs):
        super(Fitting_Task_Edit_Form, self).__init__(*args, **kwargs)
        
        # Crispy
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_class = 'form-verticle'

        self.helper.add_input(Submit('submit', 'Submit'))
        
        # Get the User IDs for user profiles where role is 'Fit'
        fitter_user_ids = User_Profile.objects.filter(role="Fit").values_list('user', flat=True)
        
        # Now filter the User queryset to those User IDs
        self.fields['user'].queryset = User.objects.filter(id__in=fitter_user_ids)

fitting_floor/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.urls import reverse_lazy, reverse
from django.db import transaction

from members.models import User_Profile
from .models import FittingTask
from .forms import Fitting_Task_Form, Fitting_Task_Edit_Form
# Generic Class Views
from django.views.generic import (
    CreateView,
    UpdateView,
    DeleteView,
)

# Create your views here.
def get_fitters_task_list():
    fitters_list = User_Profile.objects.filter(role='Fit').order_by('firstName')
    fitters_tasks = []
    today = timezone.localdate()

    print(today)
    for fitter in fitters_list:
        fitter_task_list = []
        for task in fitter.user.fitting_task.filter(date_created__date=today):
            fitter_task_list.append(task)

        fitters_tasks.append((fitter.user.username, fitter_task_list))
    
    return fitters_tasks

@login_required
def fitting_floor_home(request):
    form = Fitting_Task_Form

    context = {
        "title": "Fitting Floor",
        "form": form,
        "fitters": get_fitters_task_list(),
    }
    return render(request, "fitting_floor/fittingFloorHome.html", context)


class DeleteFittingTask(DeleteView):
    model = FittingTask
    success_url = reverse_lazy("ff:Fitting_Floor")
    template_name = "fitting_floor/deleteFittingTaskPage.html"


def addFittingTask(request):
    context = {
        "title": "Fitting Floor",
        "form": Fitting_Task_Form(),   
        "fitters_list": get_fitters_task_list()
    }
    if request.method == 'POST':
        form = Fitting_Task_Form(request.POST)
        if form.is_valid():
            form.save()
            context['form'] = form
            return redirect("ff:Fitting_Floor")
        # Add failed message here
        print("Form errors: ",form.errors)
        return redirect("ff:Fitting_Floor")
    

class UpdateFittingTask(UpdateView):
    template_name = "fitting_floor/updateFittingTaskPage.html"
    model = FittingTask
    fields = ["user", "job_code", "ancillary_code", "time_started", "time_stopped", "notes"]
    success_url = reverse_lazy('ff:Fitting_Floor')

    def get(self, request, *args, **kwargs):
        print("******The GET method has been called******")
        return render(request, "ff:Edit_Floor_Task", {"form": Fitting_Task_Edit_Form})
    

def updateFittingTask(request, taskId):
    # return HttpResponse(status=200)
    task = get_object_or_404(FittingTask, id=taskId)
    if request.method == "POST":
        form = Fitting_Task_Edit_Form(request.POST)
        if form.is_valid:
            form.save()
            return redirect("ff:Fitting_Floor")
        
    context = {
        "form": Fitting_Task_Edit_Form(instance=task)
    }
    print("*****THE GET METHOD HAS BEEN CALLED*****")
    return render(request, 'fitting_floor/test.html', context)
    

    
def testingFF(request, taskId):
    print(f"Fitting Floor task: ${taskId} is being edited")
    task = get_object_or_404(FittingTask, id=taskId)
    if request.method == "POST":
        form = Fitting_Task_Edit_Form(request.POST)
        if form.is_valid():
            form.save()
            return redirect("ff:Fitting_Floor")
    
    context = {
        "form": Fitting_Task_Edit_Form(instance=task),
        "task": task
    }
    print("*****TASK TO EDIT*****", context['task'])
    print("*****FORM TO EDIT*****", context['form'])
    return render(request, "fitting_floor/test.html", context)

fitting_floor/templates/fitting_floor/AddNewfittingFloorTaskInput.html
<div class="addTime row">
    <div class="form-style form-style-five">
        <div class="row">
            <div class="col-lg">
                <div class="form-input mt-5">
                    <form action="#">
                    {% csrf_token %}
                        <table class="table table-hover">
                            <thead>
                                <th>

                                </th>
                                {% for input in form %}
                                    <th>
                                        {{ input.label }}
                                    </th>
                                {% endfor %}
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="col">
                                        New Task
                                    </th>
                                    {% for input in form %}
                                        <td scope="col">
                                            {{ input }}
                                        </td>
                                    {% endfor %}
                                    <td>
                                        <button 
                                            id="addTask" 
                                            type="submit" 
                                            formmethod="POST" 
                                            formaction="{% url 'ff:Create_Floor_Task' %}" 
                                            class="btn btn-m btn-primary"
                                            >
                                            Add
                                            </button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

fitting_floor/templates/fitting_floor/deleteFittingTaskPage.html
{% extends 'main/base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
	



    <p>Are you sure you want to delete "{{ object }}"?</p>
    
    
    
    
        <input type="submit" class="btn btn-danger" value="Confirm">
    </form>
    
{% endblock %}

fitting_floor/templates/fitting_floor/fittingFloorHome.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}


<main id="taskTimerPage" class="container-fluid px-4">
    <div class="container-fluid">
        <!-- Header -->
        {% include 'fitting_floor/fittingFloorHeader.html' %}
        <!-- New Task Input -->
        {% include "fitting_floor/AddNewfittingFloorTaskInput.html" %}
        <!-- Todays Active Tasks -->
        {% include "fitting_floor/fittingFloorTodaysTaskTable.html" %}
    </div>

    <!-- Modal for edit interface -->
    <div class="modal fade" id="editFFModal" tabindex="-1" aria-labelledby="editFFModalLabel" aria-hidden="true">
        <div id="fittingTaskDialog" class="modal-dialog">
        <!-- Inject Modal HTML in here -->
        </div>
    </div>

    {% include "fitting_floor/test.html" %}

</main>



{% endblock content %}

fitting_floor/templates/fitting_floor/fittingFloorTodaysTaskTable.html
<ul>
    {% for fitter in fitters %}
        <div class="row border-bottom my-2 horizontal-scrollable" style="overflow-x: auto; white-space: nowrap; scroll-behavior: smooth;">
            <div class="col-1 fitter align-self-center">
                <h4 class="">
                    {{ fitter.0 }}
                </h4>
                <p>{{ fitter.1|length }} tasks</p>
            </div>
            <div class="col d-flex fitter_tasks">
            {% for task in fitter.1 %}
                    <div class="card mb-2 m-2 bg-info" style="min-width: 20rem;">
                        <div class="row g-0 justify-content-center" ">
                          <div class="col-md-8 w-100 ">
                            <div class="card-body">
                              <h5 class="card-title">{{ task.job_code }} - {{ task.ancillary_code }}</h5>
                              <p class="card-text">{{ task.time_started|time }} - {{ task.time_stopped|time }} : {{ task.elapsed_time }}</p>
                              <p class="card-text m-0"><small class="text-muted">{{ task.date_created }}</small></p>
                              <p class="card-text m-0"><small class="text-muted">task ID:{{ task.pk }}</small></p>
                            </div>
                          </div>
                            <div class="col btn-group p-2">
                                <a 
                                    class="btn btn-warning" 
                                    data-bs-toggle="modal" 
                                    data-bs-target="#exampleModal"
                                    hx-cache="false"
                                    hx-target="#exampleModal"
                                    hx-swap="outerHTML" 
                                    hx-get="{% url 'ff:Edit_Floor_Task' taskId=task.id %}">
                                    edit    
                                </a>
                                <a href="{% url 'ff:Delete_Floor_Task' pk=task.pk %}" class="btn btn-danger">
                                    delete
                                </a>
                                <button 
                                    type="button" 
                                    class="btn btn-primary" 
                                    data-bs-toggle="modal" 
                                    data-bs-target="#exampleModal"
                                    hx-get="{% url 'ff:Edit_Floor_Task' taskId=task.id %}">
                                        test
                                </button>
                            </div>
                        </div>
                    </div> 
                {% endfor %}
            </div>
        </div>
    {% endfor %}
</ul>

fitting_floor/templates/fitting_floor/test.html
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{ task.user }}: {{ task.id }}{{ task.job_code }}{{ task.ancillary_code }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="">
                    {% csrf_token %}
                    <form action="">
                        {{ form.as_p }}
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

fitting_floor/templates/fitting_floor/updateFittingTaskPage.html
{% block modal %}

<!-- Modal -->
<form 
class="modal-content"
hx-post="{{ request.path }}" >
    {% csrf_token %}
    <div class="modal-header">
        <h1 
        class="modal-title fs-5" 
        id="editFFModalLabel">
        Edit Task "{{ task }}"
        </h1>
        <button 
        type="button" 
        class="btn-close" 
        data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
    {{ form.as_p }}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <button 
            class="btn btn-primary" 
            data-bs-dismiss="modal" 
            hx-post="{% url 'ff:Edit_Floor_Task' taskId=task.pk %}"
            hx-target="#taskTimerPage"
            hx-swap="outerHTML"
        >
            Save change
        </button>
    </div>
</form>

{% endblock modal %}