MacTrack/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('members.urls')),
    path('taskTimer/', include('timesheets.urls')),
    path('reports/', include('reports.urls')),
    path('projects/', include('projects.urls')),
    path('fitting_floor/', include('fitting_floor.urls')),
]

main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.landingPage, name="Home"),
    path("login/", views.login_page, name="Log"),
]

reports/urls.py
from django.urls import path

from reports import views

urlpatterns = [
    path("", views.reports_landing_page, name="Reports_Page"),
    path("testing", views.testing_view, name="Testing"),
    path("taskTimers/", views.task_timer_reports, name='Task_Timer_Reports'),
    path("admin/", views.admin_reports_page, name='Admin_Reports'),
    path("admin/taskTimes", views.full_task_time_report, name='Task_Time_Report'),
    path("admin/projectTaskChart", views.project_task_chart, name='Project_Task_Chart'),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=40, blank=False, null=False)
    code = models.CharField(max_length=8, blank=False, null=False, unique=True)
    phone_number = models.CharField(max_length=13, blank=True, null=True)
    fax_number = models.CharField(max_length=13, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    contact_person = models.CharField(max_length=40, blank=True, null=True)

    def __str__(self):
        return self.name

class Project(models.Model):
    PROJECT_STATUS = [
        ("Des", "At Design"),
        ("Prod", "In Production"),
        ("Hold", "On Hold"),
        ("Assy", "At Assembly"),
        ("Awt", "Awaiting Delivery"),
        ("Del", "Delivered"),
        ("Can", "Cancelled"),
    ]
    customer = models.ForeignKey(Customer, on_delete=models.RESTRICT)
    description = models.CharField(max_length=144)
    is_high_priority = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    job_code = models.CharField(max_length=8, primary_key=True, blank=False, null=False)
    status = models.CharField(max_length=4, default="Des", choices=PROJECT_STATUS, null=False, blank=False)
    created_by = models.ForeignKey(User, on_delete=models.RESTRICT, blank=True, null=True)
    project_captains = models.ManyToManyField(User, related_name="projects")
    purchase_order_number = models.CharField(max_length=24, blank=True, null=True)

    class Meta:
        ordering = ['job_code']

    def __str__(self) -> str:
        return self.job_code

reports/models.py
from django.db import models

# Create your models here.

reports/forms.py
from django import forms
from timesheets.models import TaskTime

class adminProjectTaskTimeFilterForm(forms.ModelForm):
    class Meta:
        model = TaskTime
        fields = (
            "job_code",
            "ancillary_code",
            "user",
        )
        widgets = {
            "job_code": forms.SelectMultiple(
                    attrs={
                        "class": "form-select select2",
                        "placeholder": "Job Code",
                    }
                ),
            "ancillary_code": forms.SelectMultiple(
                attrs={
                    "class": "form-select select2",
                    "placeholder": "Ancillary Code",
                }
            ),
            "user": forms.SelectMultiple(
                    attrs={
                        "class": "form-select select2",
                        "placeholder": "Designer",
                    }
                ),
        }

reports/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.contrib.auth.decorators import user_passes_test, login_required
from django.utils import timezone
from django.http import HttpResponseNotAllowed

from reports.utilities import getDesignerTaskTimeChartContext, getAdminProjectTimesChartContext, testGraph
from reports.forms import adminProjectTaskTimeFilterForm

# Import Utilites
from .utilities import adminReportsContext

# Import graph components
from .templates.graphs.barChart import get_graph_components

# Import app models
from timesheets.models import TaskTime
from members.models import User_Profile

# Create your views here.

def reports_landing_page(request):
    context = {
        "reports": "Here are some reports"
    }
    return render(request, "reports/landingPage.html", context)

def task_timer_reports(request):
    userId = request.user.id
    context = getDesignerTaskTimeChartContext(userId)

    return render(request, "reports/taskTimerPage.html", context)

def dashboard_project_times_chart(request):
    # Get all user task times
    task_times = list(TaskTime.objects.filter(user=request.user.id))

    # Add up all the time for each job code
    job_code_hours = {}

    for t in task_times:
        if t.job_code not in job_code_hours:
            job_code_hours[str(t.job_code)] = t.elapsed_time
        else:
            job_code_hours[str(t.job_code)] += t.elapsed_time

    # We need lists for the input for the x and y axis's respectively
    jc_list = list(job_code_hours.keys())
    et_list = list(job_code_hours.values())


    # We want the time in hours
    if et_list is not None:
        et_list = [t.total_seconds() / 3600 for t in et_list]
    else:
        et_list = []


    script, div = get_graph_components(jc_list, et_list)

    context = {
        "reports": "Here are some task timer reports",
        "script": script,
        "div": div
    }

    return render(request, "reports/taskTimerPage.html", context)


def admin_check(user):
    userProfile = User_Profile.objects.get(user=user.id)
    return userProfile.role.startswith("Adm")

@login_required
@user_passes_test(admin_check, login_url='/reports/taskTimers/')
def admin_reports_page(request):
    context = adminReportsContext()
    return render(request, "reports/adminReportPage.html", context)


@login_required
@user_passes_test(admin_check, login_url='/reports/taskTimers/')
def full_task_time_report(request):
    context = {
        "title": "Task Times Report",
        "tasks": TaskTime.objects.all().exclude(elapsed_time=None).order_by("-date_created", "user", "job_code", "ancillary_code", "description")
    }
    return render(request, "reports/taskTimeReport.html", context)

@login_required
@user_passes_test(admin_check, login_url='/reports/taskTimers/')
def project_task_chart(request):
    if request.method == "GET":
        context = getAdminProjectTimesChartContext()
        return render(request, "reports/projectTaskChart.html", context)
    if request.method == "POST":
        print("****************************************************************** POST ******************************************************************")
        form = adminProjectTaskTimeFilterForm(request.POST)
        print(request.POST)
        if form.is_valid():
            print("form is valid")
            print("Form job_code: ", form.cleaned_data["job_code"])
            print("Form ancillary_code: ", form.cleaned_data["ancillary_code"])
            print("Form user: ", form.cleaned_data["user"])
            context = getAdminProjectTimesChartContext(input)

            return render(request, "reports/projectTaskChart.html", context)
        else:
            print("Form is not valid")
            context = getAdminProjectTimesChartContext(input)
            return render(request, "reports/projectTaskChart.html", context)
    
    return HttpResponseNotAllowed(['GET', 'POST'])

# This is WORK IN PROGRESS
# def all_jobs_total_time_report(request):
#     task_times = list(TaskTime.objects.all())

#     # job_type = {
#     #     "spares": [],
#     #     "machines": [],
#     #     "filtec": [],
#     # }

#     # main_job_codes = {}

#     for t in task_times:
#         js = t.job_code.split("-")

#     # Define ranges
#     x_axis = []
#     y_axis = []

#     script, div = get_graph_components(x_axis, y_axis)
#     context = {
#         "script": script,
#         "div": div
#     }
#     return render(request, "partials/totalJobTimeComparison.html", context)

def testing_view(request):
    context = testGraph()
    return render(request, "reports/testingPage.html", context)

reports/templates/reports/adminReportPage.html
{% extends "main/base.html" %}
{% block content %}

<main class="px-4 mt-2">
    <!-- <div class="container card-container">
        <div class="row h-20">
            <div class="designerTaskTimesCard col-sm-12 p-4 col-6 themed-grid-col">
                {% include 'partials/designerTaskTimeCard.html' %}
            </div>
        </div>
    </div> -->

    <div class="card my-2" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Designer Timesheets</h5>
            <h6 class="card-subtitle mb-2 text-muted">Table of task times</h6>
            <a href="{% url 'Task_Time_Report' %}" class="btn btn-primary">See Full History</a>
        </div>
    </div>

    <div class="card my-2" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Project Task Chart</h5>
            <h6 class="card-subtitle mb-2 text-muted">Project Component Time Chart</h6>
            <p>WIP</p>
            <a href="{% url 'Project_Task_Chart' %}" class="btn btn-primary">See Graph</a>
        </div>
    </div>


</main>

{% endblock content %}

reports/templates/reports/projectTaskChart.html
{% extends "main/base.html" %}
{% block content %}

<main class="px-4 mt-2">
    <div class="card">
        <h5 class="card-header">Project Times Chart</h5>
        <div class="card-body">
            <div>
                {{ div|safe }}
                {{ script|safe }}
            </div>
        </div>
      </div>
</main>

{% endblock content %}

reports/templates/reports/taskTimeReport.html
{% extends 'main/base.html' %}
{% load customTemplateTags %}
{% load static %}

{% block content %}
<main class="container-fluid p-4">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">Date Created</th>
                <th scope="col">Designer</th>
                <th scope="col">Job Code</th>
                <th scope="col">Description</th>
                <th scope="col">Ancillary Code</th>
                <th scope="col">Time Spent</th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
            {% if task.elapsed_time|hasTime %}
            <tr id="task-{{ task.id }}" class="clickableRow" scope="row">
                <td>{{ task.date_created | date:"d M Y" }}</td>
                <td>{{ task.user }}</td>
                <td>{{ task.job_code }}</td>
                <td>{{ task.get_description_display }}</td>
                <td>{{ task.ancillary_code.code }} - {{ task.ancillary_code.description }}</td>
                <td>{{ task.elapsed_time }}</td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
</main>

<script src="{% static 'main/js/selectTableRow.js' %}"></script>

{% endblock %}

reports/templates/reports/taskTimerPage.html
{% extends "main/base.html" %}

{% block content %}

<main class="container-fluid p-4">
    <h2>Time per Job</h2>
        <div id="graphContainer" class="col-12">
            {{ div|safe }}
            {{ script|safe }}
        </div>    
    <div>
        
    </div>
</main>    

{% endblock content %}

reports/templates/reports/testingPage.html
{% extends "main/base.html" %}
{% block content %}

<main class="px-4 mt-2">
    <div class="btnGroup m-4">
        <div class="btn-group">
            <form id="projectReportFilter" action="">
            <!-- <button type="button" class="btn btn-danger dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"> -->
                <!-- Filter Ancillary Tasks -->
            <!-- </button> -->

              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Separated link</a></li>
              </ul>
          </div>
          <div class="filterForm">
              {{ filterForm.as_p }}
          </div>
          <button class="btn btn-primary">
            Filter
          </button>
            
          </form>
          
    </div>
    <div class="card">
        <h5 class="card-header">Project Design Task Time Chart</h5>
        <div class="card-body">
            <div>
                {{ div|safe }}
                {{ script|safe }}
            </div>
        </div>
      </div>
</main>

<script>
    $(document).ready(function() {
        // Initialize Select2 on your filter fields
        $('.select2').select2({
            dropdownParent: $('#projectReportFilter'),
            // width: '100%'
        });
        $('.select2').addClass("col-4")
    });
</script>

{% endblock content %}