MacTrack/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('members.urls')),
    path('taskTimer/', include('timesheets.urls')),
    path('reports/', include('reports.urls')),
    path('projects/', include('projects.urls')),
    path('fitting_floor/', include('fitting_floor.urls')),
]

fitting_floor/urls.py
from django.urls import path

from fitting_floor import views
from .views import DeleteFittingTask, UpdateFittingTask

app_name = 'ff'

urlpatterns = [
    path("", views.fitting_floor_home, name="Fitting_Floor"),
    path("add_fitting_task", views.addFittingTask, name="Create_Floor_Task"),
    path("edit_task/<int:taskId>", views.testingFF, name="Edit_Floor_Task"),
    path("delete_task/<int:pk>/", DeleteFittingTask.as_view(), name="Delete_Floor_Task"),
]

main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.landingPage, name="Home"),
    path("login/", views.login_page, name="Log"),
]

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from members.forms import Login_Form

# Create your views here.
@login_required
def landingPage(request):
    username = request.user.username
    context = {'greeting': "Welcome to the landing page!"}
    return redirect('User_Profile', username)

def login_page(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is None:
            context = {
                'error': "Username and/or password is incorrect",
                "form": Login_Form
            }
            return render (request, 'main/loginPage.html', context)
        else:
            login(request, user)
            print ("User has been authenticated!")
            print (user)
            return redirect('User_Profile', user)
    else:
        context = {
            'form': Login_Form
        }
        return render(request, 'main/loginPage.html', context)

main/templates/partials/navbar.html
{% load static %}

<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="{% if user.username %} {% url 'User_Profile' user.username %} {% else %}  #  {% endif %}">MacTrack</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <div class="pageTitle order-1 order-lg-0 me-4 me-lg-0">
        <h1 class="navbar-brand ps-3">{{ title }}</h1>
    </div>
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0" >
        <div class="input-group">
            <!-- <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" /> -->
            <!-- <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button> -->
        </div>
    </form>
    <!-- Navbar-->
    <div class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <div class="nav-item dropdown">
            <!-- <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-user fa-fw"></i> {{ user.username }}
            </a> -->
            <a class="nav-link dropdown-toggle navbar-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-user fa-fw"></i> {{ user.username }}
            </a>
            
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'Logout' %}">Logout</a></li>
            </ul>
        </div>
    </div>
</nav>

main/templates/partials/sideMenu.html
{% load static %}
<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
        <div class="nav">
            <div class="sb-sidenav-menu-heading">User</div>
            <a class="nav-link" href="{% if user %} {% url 'User_Profile' username=user %} {% else %} # {% endif %}">
                <div class="sb-nav-link-icon"><i class="fas fa-address-card"></i></div>
                Dashboard
            </a>
            <a class="nav-link" href="{% url 'Task_Timer' %}">
                <div class="sb-nav-link-icon"><i class="fas fa-stopwatch"></i></div>
                Task Timer
            </a>
            <div class="sb-sidenav-menu-heading">Projects</div>
            <a class="nav-link" href="{% url 'Admin_Reports' %}">
                <div class="sb-nav-link-icon"><i class="fas fa-chart-simple"></i></div>
                Reports
            </a>
            <a class="nav-link" href="{% url 'Projects_Page' %}">
                <div class="sb-nav-link-icon"><i class="fas fa-folder-open"></i></div>
                Projects
            </a>
            <a class="nav-link" href="{% url 'Customers_Page' %}">
                <div class="sb-nav-link-icon"><i class="fa-regular fa-address-card"></i></div>
                Customers
            </a>
            <a class="nav-link" href="{% url 'ff:Fitting_Floor' %}">
                <div class="sb-nav-link-icon"><i class="fa-regular fa-address-card"></i></div>
                Fitting Floor
            </a>
            {% if request.user.user_profile.role == "Man" %}
            <div class="sb-sidenav-menu-heading">Members</div>
            <a class="nav-link" href="{% url 'User_List' %}">
                <div class="sb-nav-link-icon"><i class="fa-solid fa-users"></i></div>
                Users
            </a>
            {% endif %}
        </div>
    </div>
    <div class="sb-sidenav-footer">
        <div class="small">Logged in as:</div>
        {{ user.username }}
    </div>
</nav>